baseURL = "httsp://www.thatsawrapandmore.com/"
languageCode = "en-us"
title = "It's A Wrap & More"

[params]

contactEmail = "info@thatsawrapandmore.com"
phoneNumber = "469-476-2456"
cloudinary_base_url = "https://res.cloudinary.com/dx6vch6h7/image/upload"
social_facebook = "https://www.facebook.com/thatsawrapandmoreusa/"
social_instagram = "https://www.instagram.com/thats_a_wrap_andmore/"
